version: '3'

volumes:
  mysqldata: {}

services:
  web:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/app

  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    ports:
      - "${PHP_MYADMIN_PORT}:80"
